## G8 - Lavoro e Disoccupazione

In [1]:
# Import librerie per analisi dati (Pandas) e dati Istat
import os
import pandas as pd
import numpy as np
from IPython.core.display import HTML
import istat
import jsonstat

# cache dir per velocizzare analisi in locale
cache_dir = os.path.abspath(os.path.join("..", "tmp/od_la_grande_fuga", "istat_cached"))
istat.cache_dir(cache_dir)
istat.lang(0)  # lingua italiano

dir_df = os.path.join(os.path.abspath(''),'stg')

In [6]:
area_lavoro = istat.area('LAB')
area_lavoro.datasets()

[DCCV_COMPL(12):Indicatori complementari,
 DCCV_DISOCCUPT(10):Disoccupati,
 DCCV_DISOCCUPTDE(7):Disoccupati - dati destagionalizzati,
 DCCV_DISOCCUPTMENS(8):Disoccupati - dati mensili,
 DCCV_FORZLV(8):Forze di lavoro,
 DCCV_FORZLVDE(7):Forze di lavoro - dati destagionalizzati,
 DCCV_FORZLVMENS(8):Forze lavoro - dati mensili,
 DCCV_INATTIV(11):Inattivi,
 DCCV_INATTIVDE(7):Inattivi - dati destagionalizzati,
 DCCV_INATTIVMENS(8):Inattivi - dati mensili,
 DCCV_NEET(10):NEET (giovani non occupati e non in istruzione e formazione),
 DCCV_OCCUPATIMENS(8):Occupati - dati mensili,
 DCCV_OCCUPATIT(14): Occupati                                                      ,
 DCCV_OCCUPATITDE(8):Occupati - dati destagionalizzati,
 DCCV_ORELAVMED(12):Occupati per ore settimanali lavorate e numero di ore settimanali lavorate procapite,
 DCCV_POPCOND(10):Popolazione per condizione professionale,
 DCCV_TAXATVT(8):Tasso di attività,
 DCCV_TAXATVTDE(7):Tasso di attività - dati destagionalizzati,
 DCCV_TAXATVTMENS(8):Tasso di attività - dati mensili,
 DCCV_TAXDISOCCU(9):Tasso di disoccupazione,
 DCCV_TAXDISOCCUDE(7):Tasso di disoccupazione - dati destagionalizzati,
 DCCV_TAXDISOCCUMENS(8):Tasso di disoccupazione - dati mensili,
 DCCV_TAXINATT(8):Tasso di inattività,
 DCCV_TAXINATTDE(7):Tasso di inattività - dati destagionalizzati,
 DCCV_TAXINATTMENS(8):Tasso di inattività - dati mensili,
 DCCV_TAXOCCU(8):Tasso di occupazione,
 DCCV_TAXOCCUDE(7):Tasso di occupazione - dati destagionalizzati,
 DCCV_TAXOCCUMENS(8):Tasso di occupazione - dati mensili,
 DCIS_RICSTAT(6):Ricostruzione statistica delle serie regionali di popolazione del periodo 1/1/2002-1/1/2014,
 DCSC_COSTLAVSTRUT_1(6):Imprese ed enti pubblici con almeno 10 dipendenti,
 DCSC_COSTLAVULAOROS_1(5):Indicatori - Imprese con dipendenti,
 DCSC_GI_COS(6):Imprese con almeno 500 dipendenti,
 DCSC_GI_OCC(6):Posizioni lavorative - Imprese con almeno 500 dipendenti,
 DCSC_GI_ORE(6):Ore lavorate - Imprese con almeno 500 dipendenti,
 DCSC_GI_RE(6):Retribuzioni lorde - Imprese con almeno 500 dipendenti,
 DCSC_ORE10_1(5):Ore lavorate - Imprese con almeno 10 dipendenti,
 DCSC_OROS_1(5):Posizioni lavorative alle dipendenze,
 DCSC_POSTIVAC_1(5):Posti vacanti - Imprese con almeno 10 dipendenti,
 DCSC_RETRATECO1(6):Retribuzioni contrattuali per settore economico (Ateco),
 DCSC_RETRCASSCOMPPA(7):Retribuzioni contrattuali nella Pubblica amministrazione,
 DCSC_RETRCONTR1C(6):Retribuzioni contrattuali per tipo di contratto,
 DCSC_RETRCONTR1O(6):Orario contrattuale, ferie e altre riduzioni orarie - dipendenti a tempo pieno,
 DCSC_RETRCONTR1T(6):Tensione contrattuale,
 DCSC_RETRULAOROS_1(5):Retribuzioni lorde - Imprese con dipendenti]

In [60]:
# Indicatori di lavoro - Tasso Disoccupazione
ds_lavoro = area_lavoro.dataset('DCCV_TAXDISOCCU')
ds_lavoro.dimension('Classe di età')

'Classe di età' (3:'20-24 anni', 4:'15-24 anni', 8:'25-34 anni', 9:'35-54 anni', 11:'35 anni e più', 14:'35-44 anni', 17:'45-54 anni', 19:'55 anni e più', 21:'55-64 anni', 22:'15-64 anni', 28:'15 anni e più', 30:'15-29 anni', 31:'15-74 anni', 32:'18-29 anni')

In [62]:
# NORD
spec_n = {
    "Territorio":3,
    "Sesso":3,
    "Cittadinanza":3,
    "Durata disoccupazione":3,
    "Titolo di studio":12,
    "Classe di età":28
}

#SUD
spec_s = {
    "Territorio":88,
    "Sesso":3,
    "Cittadinanza":3,
    "Durata disoccupazione":3,
    "Titolo di studio":12,
    "Classe di età":28
}

In [75]:
def disoccupati(ds, spec,nome):
    c = ds.getvalues(spec)
    ds = c.dataset(0)
    df = ds.to_data_frame('Tempo e frequenza')
    df.reset_index(level=0, inplace=True)
    df.columns = ['Anno',nome]
    df = df[(df['Anno'].str.contains("T")==False)]
    return df

In [80]:
df_s = disoccupati(ds_lavoro, spec_s, 'Sud')
df_n = disoccupati(ds_lavoro, spec_n, 'Nord')

In [82]:
df = pd.merge(df_n,df_s, how='inner', on=['Anno', 'Anno'])
df = df.set_index(['Anno'])
df

      Nord    Sud
Anno
1977  5.76   8.05
1978  6.09   7.98
1979  6.14   8.60
1980  6.15   8.89
1981  6.76   9.44
1982  7.63  10.06
1983  8.89  10.70
1984  9.38  11.39
1985  9.14  11.87
1986  8.83  13.04
1987  8.54  14.72
1988  7.43  15.74
1989  6.53  15.95
1990  5.77  14.96
1991  5.60  14.12
1992  6.01  13.87
1993  6.66  15.17
1994  7.32  16.59
1995  7.13  18.21
1996  6.92  18.59
1997  6.80  18.99
1998  6.50  19.65
1999  5.79  19.66
2000  4.99  18.84
2001  4.26  17.26
2002  4.17  16.27
2003  4.04  16.07
2004  4.30  14.80
2005  4.25  14.21
2006  3.79  12.17
2007  3.48  10.96
2008  3.87  12.00
2009  5.27  12.45
2010  5.87  13.31
2011  5.71  13.54
2012  7.36  17.11
2013  8.38  19.69
2014  8.61  20.67
2015  8.06  19.40